name: network_card
device_type: network
device_class: consumer
identification:
  vendor_id: 0x8086  # Intel Corporation
  device_id: 0x10D3  # 82574L Gigabit Network Connection
  subsystem_vendor_id: 0x8086
  subsystem_device_id: 0x10D3
  class_code: 0x020000  # Ethernet controller
registers:
  command: 0x0006  # Memory Space + Bus Master
  status: 0x0210   # Cap List + Fast B2B
  revision_id: 0x01
  cache_line_size: 0x10
  latency_timer: 0x00
  header_type: 0x00
  bist: 0x00
capabilities:
  max_payload_size: 512
  msi_vectors: 1
  msix_vectors: 0
  supports_msi: true
  supports_msix: false
  supports_power_management: true
  supports_advanced_error_reporting: false
  link_width: 1
  link_speed: "2.5GT/s"
custom_properties:
  description: "Intel 82574L Gigabit Ethernet Controller"
  manufacturer: "Intel Corporation"
  typical_use_case: "Network interface card for PCIe x1 slot"